var random = require('./random.js');
var geometry = require('./geometry.js');
var eightball = require('./eightball.js');
var palindrome = require('./palindrome.js');
var pig = require('./piglatin.js');
var five = require('./five.js');
console.log( random(10) );
console.log( geometry.area(4,5) );
console.log( eightball() );
console.log( palindrome('racecar') );
console.log( palindrome('hello') );
console.log( palindrome('a man a plan a canal panama') );
//console.log( pig.toPig() );
//console.log( pig.fromPig() );
console.log( five() );
console.log( five.upHigh() );
console.log( five.downLow() );
console.log( five.tooSlow() );
console.log( five.roman() );
console.log( five.morseCode() );
console.log( five.negative() );
console.log( five.loud() );
console.log( five.smooth() );
